### ISSUE TITLE
Windows version crashing

### ISSUE THREAD

**Issue by cjs8972** [KKBOX/CompassApp#278]
Just bought Compass - I'm running Compass 1.28.1 on a Windows 64 machine, it completely breaks when trying to import "compass" or import "compass/css3" and also is crashing quite frequently. 

Errors include (trying to import compass):
/*
Errno::ESRCH: No such process - No message available

Backtrace:
org/jruby/RubyFile.java:592:in `chmod'

**Comment by hlb** [comment]
fixed in v1.29 and will release soon.

**Comment by Wicked0ne** [comment]
I'm using v1.29 on windows 8.1 x64 and I still have this issue. Any ideas?

**Comment by hlb** [comment]
@Wicked0ne are you running Compass.app in restricted permission? i.e. not an admin account

**Comment by Wicked0ne** [comment]
@hlb Yea. I'm running it normal user and NOT admin.

**Comment by hlb** [comment]
@Wicked0ne can you try it with admin privilege? I guess there is some permission issue in your system :-/

**Comment by Tailo** [comment]
same problem

/*
Errno::ESRCH: No such process - No message available

Backtrace:
org/jruby/RubyFile.java:613:in `chmod'
C:/Users/OliverJulius/Desktop/compass.app.windows.1.29/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/util.rb:1257:in `atomic_create_and_write_file'
org/jruby/ext/thread/Mutex.java:149:in `synchronize'

error comes when using
@import "compass/css3";

no problem when using
@import "compass/reset";

windows 7 64, Java Version 8, Update 40 (build 1.8.0_40-b26), Ruby (rubyinstaller-2.2.1)

**Comment by jofranlirio** [comment]
same problem

Errno::ESRCH: No such process - No message available
Backtrace:
org/jruby/RubyFile.java:613:in `chmod'
C:/Users/jofran/Downloads/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/util.rb:1257:in `atomic_create_and_write_file'
org/jruby/ext/thread/Mutex.java:149:in `synchronize'

When i import "compass/utilities" and "compass/typography" this error comes

compass app version 1.29
windows 7, java 8 update 65 (build 1.8.0_65-b17)

**Comment by bioform** [comment]
It fails during "chmod" operation for sass file cache on Windows OS. So just turn off sass cache or just wait a fix...

**Comment by drimlike** [comment]
Did you guys find any workaround? Or a solution? I'm having the exact same issue...

**Comment by ToniHenrikssonGIT** [comment]
> It fails during "chmod" operation for sass file cache on Windows OS. So just turn off sass cache or just wait a fix...

This worked for me, thank you.
